Component (typography)
jhonderquintero/cryptocurrency-app pull request #3
Opened 2022-06-19 15:53 UTC by ricardovera76

Created Necessary Files for Typography Atom component and functionality

2022-06-22 16:22 UTC, jhonderquintero requested changes
I left some comments, feel free to reply if you have any better idea on what i purpose.

2022-06-22 16:22 UTC, jhonderquintero commented on src/components/atoms/Button/Button.tsx
> +  return (buttonClases[buttonVariant] || buttonClases['normal'])();
If you are setting buttonVariant with a defaultValue === 'normal'. Is not necessary the conditional in the return, 'cause always the first sentence in the OR operator will return true.

2022-06-24 00:11 UTC, ricardovera76 commented on src/components/atoms/Button/Button.tsx
> +  return (buttonClases[buttonVariant] || buttonClases['normal'])();
ok, thanks

2022-06-24 00:12 UTC, ricardovera76 commented on src/components/atoms/Typography/index.tsx
> +  if (variant.indexOf('heading') !== -1) {
to check what size of a heading will be used eg.: heading, heading-lg, heading-sm, each one will represent a h[x] semantic tag

2022-06-24 00:12 UTC, ricardovera76 commented on src/components/atoms/Typography/styles.style.ts
> +const textLg = 'font-Nunito text-2xl color-slate-100 dark:text-white';
🤔 ok

2022-06-25 18:34 UTC, jhonderquintero approved these changes

2022-06-25 22:54 UTC, merged